title: "Evair Cunha"
email: "ejsc@cin.ufpe.br"
description: "Researcher in Artificial Intelligence"
baseurl: "" # deixe vazio para o domínio principal
url: "https://ver0z.github.io" # substitua pelo seu URL
github_username: ver0z
